export const siteConfig = {
  name: "Zox News",
  description: "Your source for the latest news and stories",
  logo: "/images/logos/logo-large.png",
  logoNav: "/images/logos/logo-nav.png",
  logoFoot: "/images/logos/logo-large.png",
  copyright: "Copyright © 2025 Zox News Theme. Theme by MVP Themes.",
  menu: [
    { label: "Features", href: "#" },
    { label: "Buy Theme", href: "https://themeforest.net/item/zox-news-professional-wordpress-news-magazine-theme/20381541" },
    { label: "Entertainment", href: "/category/entertainment" },
    { label: "Politics", href: "/category/politics" },
    { label: "Fashion", href: "/category/fashion" },
    { label: "Sports", href: "/category/sports" },
    { label: "Tech", href: "/category/tech" },
    { label: "Business", href: "/category/business" },
    { label: "Shop", href: "/shop" },
  ],
  footerMenu: [
    { label: "Buy Theme", href: "https://themeforest.net/item/zox-news-professional-wordpress-news-magazine-theme/20381541" },
    { label: "Entertainment", href: "/category/entertainment" },
    { label: "Fashion", href: "/category/fashion" },
    { label: "Sports", href: "/category/sports" },
    { label: "Business", href: "/category/business" },
    { label: "Shop", href: "/shop" },
  ],
  social: {
    facebook: "https://facebook.com",
    twitter: "https://x.com",
    instagram: "https://instagram.com",
    youtube: "https://youtube.com",
    pinterest: "",
    tiktok: "",
    linkedin: "",
    tumblr: "",
  },
};
