export const siteConfig = {
  name: "StartupNews.fyi",
  description: "Your source for startup news and stories",
  logo: "/images/logos/startupnews-logo.png",
  logoNav: "/images/logos/startupnews-logo.png",
  logoFoot: "/images/logos/startupnews-logo.png",
  copyright: "Copyright © 2025 StartupNews.fyi",
  menu: [
    { label: "FUNDING TRACKER", href: "/funding" },
    {
      label: "SECTORS",
      href: "/sectors",
      hasDropdown: true,
      children: [
        { label: "AI & DeepTech", href: "/sectors/ai-deeptech" },
        { label: "Fintech", href: "/sectors/fintech" },
        { label: "eCommerce", href: "/sectors/ecommerce" },
        { label: "Blockchain", href: "/sectors/blockchain" },
        { label: "Healthtech", href: "/sectors/healthtech" },
        { label: "Social Media", href: "/sectors/social-media" },
        { label: "EV & Mobility", href: "/sectors/ev-mobility" },
      ]
    },
    { label: "EVENTS", href: "/events" },
  ],
  footerMenu: [
    { label: "FUNDING TRACKER", href: "/funding" },
    { label: "SECTORS", href: "/sectors" },
    { label: "EVENTS", href: "/events" },
    { label: "Entertainment", href: "/category/entertainment" },
    { label: "Business", href: "/category/business" },
    { label: "Tech", href: "/category/tech" },
    { label: "Privacy Policy", href: "/privacy-policy" },
    { label: "Terms and Conditions", href: "/terms-and-conditions" },
    { label: "Return and Refund Policy", href: "/return-refund-policy" },
  ],
  social: {
    facebook: "https://facebook.com",
    twitter: "https://x.com",
    instagram: "https://instagram.com",
    youtube: "https://youtube.com",
    pinterest: "",
    tiktok: "",
    linkedin: "https://linkedin.com",
    tumblr: "",
  },
  /** Fly-out (toggle) menu: expandable sections + simple links. id used for accordion state. */
  flyMenu: [
    {
      id: "sectors",
      label: "SECTORS",
      href: "/sectors",
      children: [
        { label: "AgriTech", href: "/sectors/agritech" },
        { label: "AI", href: "/sectors/ai" },
        { label: "eCommerce", href: "/sectors/ecommerce" },
        { label: "EdTech", href: "/sectors/edtech" },
        { label: "FoodTech", href: "/sectors/foodtech" },
        { label: "E-Sports", href: "/sectors/e-sports" },
        { label: "HealthTech", href: "/sectors/healthtech" },
        { label: "Social Media", href: "/sectors/social-media" },
        { label: "Web 3.0", href: "/sectors/web3" },
        { label: "SpaceTech", href: "/sectors/spacetech" },
        { label: "CleanTech", href: "/sectors/cleantech" },
        { label: "Cyber Security", href: "/sectors/cyber-security" },
        { label: "D2C", href: "/sectors/d2c" },
        { label: "EV Mobility", href: "/sectors/ev-mobility" },
      ],
    },
    {
      id: "events",
      label: "EVENTS",
      href: "/events",
      children: [
        { label: "Dubai", href: "/events/dubai" },
        { label: "Delhi NCR", href: "/events/delhi-ncr" },
        { label: "Bengaluru", href: "/events/bengaluru" },
        { label: "Hyderabad", href: "/events/hyderabad" },
        { label: "Mumbai", href: "/events/mumbai" },
      ],
    },
    { label: "SUBMIT YOUR EVENT", href: "/submit-event", dividerBefore: true },
    { label: "PARTNER WITH US", href: "/partner" },
    {
      id: "press",
      label: "PRESS RELEASE",
      href: "/press",
      children: [{ label: "Submit", href: "/press/submit" }],
    },
    { label: "ADVERTISE WITH US", href: "/advertise-with-us", dividerBefore: true },
    { label: "ABOUT US", href: "/about" },
    { label: "CONTACT US", href: "/contact-us" },
  ],
};
